Repository Innovacion-tec-4-0/Practica_Profesionalizante_I, pull requests merged in 2024-09, with the labels that each got.

#14 simulador iot
  sensor_data.json
  simulador_iot_sensores.py
Labels: documentation

#15 Update JsonData.py
  sprint_3/SiMonAmMu/DB/JsonData.py
Labels: enhancement

#17 Victoria
  Sprint_1/Proyecto general - Práctica profesionalizante I.pdf
  Sprint_2/Analisis de los requeriminetos - Práctica profesionalizante I.pdf
  sensor_data.json
  sprint_3/.vscode/c_cpp_properties.json
  sprint_3/.vscode/launch.json
  sprint_3/.vscode/settings.json
  sprint_3/SiMonAmMu/.vscode/settings.json
  sprint_3/SiMonAmMu/DB/__pycache__/conexion_db.cpython-312.pyc
  sprint_3/SiMonAmMu/DB/__pycache__/tabla.cpython-312.pyc
  sprint_3/SiMonAmMu/DB/mq2.py
  sprint_3/SiMonAmMu/docs/estructura_proyecto.txt
  sprint_3/SiMonAmMu/pruebas_jsonYdb/JsonData.py
  sprint_3/SiMonAmMu/pruebas_jsonYdb/data_recept.py
  sprint_3/SiMonAmMu/pruebas_jsonYdb/main.py
  sprint_3/SiMonAmMu/pruebas_jsonYdb/mqtt_to_json.py
  sprint_3/SiMonAmMu/pruebas_jsonYdb/santi.py
  sprint_3/SiMonAmMu/pruebas_jsonYdb/script.py
  sprint_3/Sim_datos_Dashboard/sensor_data.json
  sprint_3/Sim_datos_Dashboard/simulador_iot_sensores.py
Labels: documentation

#18 Victoria
  Sprint_0/Proyecto general - Práctica profesionalizante I.pdf
  Sprint_0/sprint-1.pdf
  Sprint_1/Analisis de los requeriminetos - Práctica profesionalizante I.pdf
  Sprint_1/CuestionarioparaRelevamientodeMuseos.pdf
  Sprint_1/GANTT -Pentadevs Museo.xlsx
Labels: documentation

#19 change name
  sprint_2/Proyecto general - Diseño e Implementación - Práctica profesionalizante I.pdf
  sprint_2/SiMonAmMu/.gitignore
  sprint_2/SiMonAmMu/.vscode/extensions.json
  sprint_2/SiMonAmMu/DB.code-workspace
  sprint_2/SiMonAmMu/DB/conexion_db.py
  sprint_2/SiMonAmMu/DB/mq2.py
  sprint_2/SiMonAmMu/DB/simonammu.sql
  sprint_2/SiMonAmMu/DB/tabla.py
  sprint_2/SiMonAmMu/diagram.json
  sprint_2/SiMonAmMu/docs/estructura_proyecto.txt
  sprint_2/SiMonAmMu/include/README
  sprint_2/SiMonAmMu/lib/README
  sprint_2/SiMonAmMu/platformio.ini
  sprint_2/SiMonAmMu/scripts/estruct.py
  sprint_2/SiMonAmMu/src/main.cpp
  sprint_2/SiMonAmMu/test/README
  sprint_2/SiMonAmMu/wokwi.toml
  sprint_2/Sim_datos_Dashboard/sensor_data.json
  sprint_2/Sim_datos_Dashboard/simulador_iot_sensores.py
  sprint_2/configuraciones.txt
  sprint_2/mosquitto.conf
Labels: documentation

#21 "sprint 2"
  Sprint_2/Sprint-2-Entregable.pdf
Labels: documentation, enhancement

#20 "base de datos,esp32,subscriptor"
  sprint_2/implementacionMQ-2/conexion.py
  sprint_2/implementacionMQ-2/envio_mqtt_mq2.ino
  sprint_2/implementacionMQ-2/mq2-db.sql
  sprint_2/implementacionMQ-2/mq2.py
  sprint_2/implementacionMQ-2/tabla.py
Labels: documentation, enhancement
